### ISSUE TITLE
test generated RPMs

### ISSUE THREAD

**Issue by svenwltr** [rebuy-de/nginx-builder#5]
something like
1. generate RPM
2. install RPM
3. add full featured Nginx configuration
4. start Nginx
5. query Nginx

**Comment by svenwltr** [comment]
@rebuy-de/it-platform What do you think about this?

**Comment by bjoernhaeuser** [comment]
Would do it, but not yet

**Comment by florian-zeidler** [comment]
Sounds great, can we start rolling out the new nginx before we finish the rest? So we can minimize the risk?

**Comment by svenwltr** [comment]
@das-vinculum We're on it.

**Comment by bjoernhaeuser** [comment]
Closing this, project is EOL.
